#FROM php:7.0-cli
#COPY . /usr/src/myapp
#WORKDIR /usr/src/myapp
#CMD [ "php", "./your-script.php" ]
#
FROM php:latest
MAINTAINER Cristofos/main
COPY . /usr/src/main
RUN pwd
WORKDIR /usr/src/main
#CMD [ "php", "./i.php" ]